export const SET_ALL_POSTS = 'SET_ALL_POSTS'
export const ADD_NEW_POST = 'ADD_NEW_POST'
export const DELETE_POST = 'DELETE_POST'
export const LIKE_POST = 'LIKE_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const GET_POST = 'GET_POST'